In [22]:
import pandas as pd
import numpy as np

# Your specific path
file_path = r"C:\Users\User\Documents\GitHub\Final_Year_Project\c_matrix.xlsx"

try:
    # Load the matrix
    df = pd.read_excel(file_path, index_col=0)
    matrix = df.to_numpy()

    # --- THIS PART SHOWS THE FULL MATRIX ---
    # threshold=np.inf tells numpy to never truncate the output
    # linewidth=np.inf prevents it from wrapping rows to the next line
    np.set_printoptions(threshold=np.inf, linewidth=np.inf)

    print(matrix)

    print(f"Matrix shape: {matrix.shape}")
except Exception as e:
    print(f"Error: {e}")

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 

In [29]:
import numpy as np

# Define all the matrices from the provided data
matrices = [
    np.array([[0, 0], [1, 1]]),
    
    np.array([[-0.33632213+0.00500396j, 1.33632213-0.00500396j],
              [0.66367787+0.00500396j, 0.33632213-0.00500396j]]),
    
    np.array([[-0.31856565-0.36373344j, 0.65169063-0.57842847j],
              [0.65169063-0.57842847j, -0.31856565-0.36373344j]]),
    
    np.array([[-0.22159993-0.34438483j, 0.76392982-0.49551698j],
              [0.76392982-0.49551698j, -0.22159993-0.34438483j]]),
    
    np.array([[-0.49113264-0.00325867j, 1.49113264+0.00325867j],
              [0.50886736-0.00325867j, 0.49113264+0.00325867j]]),
    
    np.array([[-0.07812507-0.2277672j, 0.91503249-0.31944771j],
              [0.91503249-0.31944771j, -0.07812507-0.2277672j]]),
    
    np.array([[0.73432065-0.0008892j, 0.26567935+0.0008892j],
              [1.73432065-0.0008892j, -0.73432065+0.0008892j]]),
    
    np.array([[-0.01427048-0.10369847j, 0.98417549-0.13976658j],
              [0.98417549-0.13976658j, -0.01427048-0.10369847j]]),
    
    np.array([[-0.47191599-0.0013089j, 0.18937016-0.00115013j, 0.11270263+0.00134534j, 0.22216727-0.00133587j],
              [0.18939397-0.00113899j, -0.47210042-0.0013968j, 0.11266354+0.00132602j, 0.22208955-0.00137257j],
              [0.12620802+0.00107429j, 0.12614842+0.00104515j, -0.64823641+0.00417902j, 0.147996+0.00123512j],
              [0.21248202-0.0012442j, 0.21238099-0.00129181j, 0.12639742+0.00150767j, -0.40774718-0.00147333j]]),
    
    np.array([[-0.0159992-0.10957509j, 0.98231462-0.14776475j],
              [0.98231462-0.14776475j, -0.0159992-0.10957509j]]),
    
    np.array([[9.98968866e-01-9.31856567e-06j, 1.03113430e-03+9.31856567e-06j],
              [1.99896887e+00-9.31856567e-06j, -9.98968866e-01+9.31856567e-06j]]),
    
    np.array([[-0.00392442-0.06221234j, 0.99606391-0.06292437j],
              [0.99606391-0.06292437j, -0.00392442-0.06221234j]]),
    
    np.array([[9.98660501e-01-5.05903542e-07j, 1.33949910e-03+5.05903542e-07j],
              [1.99866050e+00-5.05903542e-07j, -9.98660501e-01+5.05903542e-07j]]),
    
    np.array([[-0.4202751-0.47433809j, 0.5783524-0.51300064j],
              [0.5783524-0.51300064j, -0.4202751-0.47433809j]]),

    np.array([[0, 1], [1, 0]]),

    np.array([[-0.01600867-0.10959351j, 0.98231067-0.14779682j],
              [0.98231067-0.14779682j, -0.01600867-0.10959351j]]),
    np.array([[0, 1], [1, 0]]),
    np.array([[0.13575855-0.005519j, 0.42708568+0.00353202j, 0.21448661-0.00079814j],
              [0.71827438-0.00122385j, -0.45345737+0.00521486j, 0.10321221+0.00110228j],
              [0.41748417-0.00429515j, 0.11945695+0.00168284j, -0.68230118+0.00030414j]]),
    
    np.array([[-0.1346718-0.28800278j, 0.85549994-0.40491459j],
              [0.85549994-0.40491459j, -0.1346718-0.28800278j]]),
    
    np.array([[-0.35205592+0.00674814j, 1.35205592-0.00674814j],
              [0.64794408+0.00674814j, 0.35205592-0.00674814j]]),
    
    np.array([[-0.11421091-0.23896152j, 0.86050711-0.42618168j],
              [0.86050711-0.42618168j, -0.11421091-0.23896152j]]),
    
    np.array([[-0.75530473+0.00343281j, 1.75530473-0.00343281j],
              [0.24469527+0.00343281j, 0.75530473-0.00343281j]]),
    
    np.array([[-0.04374299-0.17666278j, 0.9526288-0.24032426j],
              [0.9526288-0.24032426j, -0.04374299-0.17666278j]]),

    np.array([[0, 1], [1, 0]]),

    np.array([[0.0049712-0.00146809j, 0.95903367-0.26417827j],
              [0.95903367-0.26417827j, 0.0049712-0.00146809j]]),
    
    np.array([[-0.48074787+0.00185738j, 1.48074787-0.00185738j],
              [0.51925213+0.00185738j, 0.48074787-0.00185738j]]),
    
    np.array([[-0.25270185-0.29857033j, 0.68766833-0.60061615j],
              [0.68766833-0.60061615j, -0.25270185-0.29857033j]]),
    
    np.array([[-3.01654335e-01-7.27565213e-03j, 4.88415382e-01+3.64232144e-03j, 1.69699987e-01-2.58377881e-03j, 2.46665622e-02-3.25335158e-04j, 6.81624572e-03+4.00806870e-05j],
              [4.41622408e-01-2.42395208e-03j, -1.76919980e-01+8.65815811e-03j, 2.00030920e-01+1.14268339e-03j, 2.90740435e-02+2.25279202e-04j, 8.03098180e-03+2.15418214e-04j],
              [2.09747764e-01-4.16911899e-03j, 2.73436410e-01+3.83072140e-03j, -6.08989596e-01-1.51192227e-03j, 1.38112943e-02-9.16697651e-05j, 3.81607355e-03+4.74417716e-05j],
              [3.66034907e-02-6.83961473e-04j, 4.77159950e-02+7.25306735e-04j, 1.65818402e-02-1.24073540e-04j, -9.31765314e-01-1.82596269e-04j, 6.65924805e-04+9.07188174e-06j],
              [1.03720019e-02+1.38040747e-06j, 1.35122331e-02+4.59808528e-04j, 4.69765663e-03+5.32466936e-05j, 6.82785993e-04+9.12945264e-06j, -9.80670774e-01+3.12012554e-04j]]),
    
    np.array([[-0.04405298-0.17722816j, 0.9523104-0.2411257j],
              [0.9523104-0.2411257j, -0.04405298-0.17722816j]]),
    
    np.array([[-0.25794182+4.13733799e-05j, 1.25794182-4.13733799e-05j],
              [0.74205818+4.13733799e-05j, 0.25794182-4.13733799e-05j]]),
    
    np.array([[-0.00146431-0.02464489j, 0.99438143-0.09414694j],
              [0.99438143-0.09414694j, -0.00146431-0.02464489j]]),
    
    np.array([[-0.93118944+3.03039917e-05j, 1.93118944-3.03039917e-05j],
              [0.06881056+3.03039917e-05j, 0.93118944-3.03039917e-05j]]),
    
    np.array([[7.73514804e-05-0.00469485j, 9.99668324e-01-0.01785637j],
              [9.99668324e-01-0.01785637j, 7.73514804e-05-0.00469485j]]),

    np.array([[0, 1], [1, 0]]),

    np.array([[-0.00822655-0.07379317j, 0.98858779-0.12338457j],
              [0.98858779-0.12338457j, -0.00822655-0.07379317j]]),
    
    np.array([[0, 1], [1, 0]]),

    np.array([[-0.02353949-0.13114762j, 0.97448622-0.17818419j],
              [0.97448622-0.17818419j, -0.02353949-0.13114762j]]),
    
    np.array([[0.6527501-2.26345181e-03j, 0.02561627+3.17800417e-04j, 0.31098219+1.73160272e-03j],
              [0.14529191+8.24856725e-04j, -0.96947524+4.14088002e-04j, 0.00574296+1.17761091e-04j],
              [1.50745818-3.08830853e-03j, 0.00490849+9.62875846e-05j, -0.68327486+1.84936381e-03j]]),
    
    np.array([[-0.54056824-0.33097366j, 0.3956228-0.65689528j],
              [0.3956228-0.65689528j, -0.54056824-0.33097366j]]),
    
    np.array([[0, 1], [1, 0]]),

    np.array([[-0.11785927-0.27322296j, 0.8735043-0.38158973j],
              [0.8735043-0.38158973j, -0.11785927-0.27322296j]]),
    
    np.array([[-0.80245351+0.00010593j, 1.80245351-0.00010593j],
              [0.19754649+0.00010593j, 0.80245351-0.00010593j]]),
    
    np.array([[-0.01819723-0.11657709j, 0.97995193-0.1573114j],
              [0.97995193-0.1573114j, -0.01819723-0.11657709j]]),
    
    np.array([[-0.22485773+0.00674892j, 1.22485773-0.00674892j],
              [0.77514227+0.00674892j, 0.22485773-0.00674892j]]),
    
    np.array([[0.00123578-0.00011127j, 0.99675787-0.0631897j],
              [0.99675787-0.0631897j, 0.00123578-0.00011127j]]),
    
    np.array([[-0.97102719-3.13319507e-04j, 0.0291711-4.27862230e-04j, 0.00568713-4.60300396e-05j, 0.00568713-4.60300396e-05j, 0.00534055-4.25723504e-05j],
              [0.0147495-1.90167076e-04j, 0.00343492-1.92620023e-03j, 0.19696132+1.57704071e-04j, 0.19696132+1.57704071e-04j, 0.18495828+1.70693822e-04j],
              [0.00482384-4.19629554e-05j, 0.33042202-5.21570455e-04j, -0.67184059+7.46217603e-04j, 0.06441272+3.21694886e-04j, 0.06048731+3.09481531e-04j],
              [0.00482384-4.19629554e-05j, 0.33042202-5.21570455e-04j, 0.06441272+3.21694886e-04j, -0.67184059+7.46217603e-04j, 0.06048731+3.09481531e-04j],
              [0.00457563-3.92265196e-05j, 0.31341978-4.55197093e-04j, 0.06109824+3.12848686e-04j, 0.06109824+3.12848686e-04j, -0.68872655+7.47084534e-04j]]),
    
    np.array([[0.00123578-0.00011127j, 0.99675787-0.0631897j],
              [0.99675787-0.0631897j, 0.00123578-0.00011127j]]),

    np.array([[0, 1], [1, 0]]),

    np.array([[-0.20462834-0.33361586j, 0.78019381-0.48381641j],
              [0.78019381-0.48381641j, -0.20462834-0.33361586j]]),
    
    np.array([[-0.00705406-0.07440707j, 0.99171657-0.10004968j],
              [0.99171657-0.10004968j, -0.00705406-0.07440707j]]),
    
    np.array([[0.95105632-0.00088082j, 0.04894368+0.00088082j],
              [1.95105632-0.00088082j, -0.95105632+0.00088082j]]),
    
    np.array([[-0.01609175-0.12395725j, 0.98383294-0.12798772j],
              [0.98383294-0.12798772j, -0.01609175-0.12395725j]]),

    np.array([[0, 1], [1, 0]]),

    np.array([[-0.00928419-0.07806731j, 0.98726289-0.13060105j],
              [0.98726289-0.13060105j, -0.00928419-0.07806731j]]),
    np.array([[0]]),
]

# Calculate total size
total_size = sum(m.shape[0] for m in matrices)
print(f"Total matrix size: {total_size} × {total_size}")

# Construct block diagonal matrix
S = np.zeros((total_size, total_size), dtype=complex)

current_pos = 0
for mat in matrices:
    size = mat.shape[0]
    S[current_pos:current_pos+size, current_pos:current_pos+size] = mat
    current_pos += size

print(f"\nBlock diagonal matrix S constructed successfully!")
print(f"Shape: {S.shape}")
print(f"Number of blocks: {len(matrices)}")
print(f"\nBlock sizes: {[m.shape[0] for m in matrices]}")

# Save to file
np.save('block_diagonal_matrix_119x119.npy', S)
print("\nMatrix saved to 'block_diagonal_matrix_119x119.npy'")


print(S[:119, :119])

Total matrix size: 119 × 119

Block diagonal matrix S constructed successfully!
Shape: (119, 119)
Number of blocks: 55

Block sizes: [2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 1]

Matrix saved to 'block_diagonal_matrix_119x119.npy'
[[ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j  0.000

In [ ]:
import numpy as np

C=matrix
def perform_propagation_analysis(S, C, a1_known=1.0, source_idx=0):
    """
    Implements Equation 4.67: M(2:n,2:n) * a(2:n) = -M(2:n,1) * a1
    """
    n = S.shape[0]
    I = np.eye(n, dtype=complex)
    
    # Calculate Network Matrix M (Equation 4.66)
    # M = I - C*S
    M = I - np.matmul(C, S)
    
    # Indices for the unknown waves (indices 1 to 118 in Python logic)
    unknown_indices = np.delete(np.arange(n), source_idx)
    
    # --- Partitioning per Equation 4.67 ---
    
    # Left Hand Side: M(2:n, 2:n)
    A_matrix = M[np.ix_(unknown_indices, unknown_indices)]
    
    # Right Hand Side: -M(2:n, 1) * a1
    # Note: source_idx is usually 0 (Node 1)
    b_vector = -M[unknown_indices, source_idx] * a1_known
    
    # --- Solve the Linear System ---
    try:
        # Solve for the incident waves a2 through an
        a_unknown = np.linalg.solve(A_matrix, b_vector)
    except np.linalg.LinAlgError:
        # Fallback if matrix is singular (common in large ideal models)
        print("System is singular, using least-squares solver.")
        a_unknown = np.linalg.lstsq(A_matrix, b_vector, rcond=None)[0]
    
    # --- Final Results Construction ---
    
    # Incident Wave Vector (A)
    a_full = np.zeros(n, dtype=complex)
    a_full[source_idx] = a1_known
    a_full[unknown_indices] = a_unknown
    
    # Propagated Wave Vector (B) (Equation 4.60: b = S * a)
    b_full = np.matmul(S, a_full)
    
    return a_full, b_full

# --- Execution ---
# Replace S_data and C_data with your actual variables
a_results, b_results = perform_propagation_analysis(S, C, a1_known=1.0)

print("Incident Waves (A):")
print(a_results)
print("Reflected Waves (B):")
print(b_results)

System is singular, using least-squares solver.
Incident Waves (A):
[ 1.00000000e+00+0.00000000e+00j -4.15738194e-01-8.11149787e-02j  5.84261806e-01-8.11149787e-02j -1.64050263e-01-8.39170903e-02j -3.46421787e-02-1.21755048e-02j  3.32573875e-01-7.83128672e-02j  7.71243330e-02+4.85249200e-02j  1.78044056e-01-2.26926743e-01j  1.94289029e-15-8.04911693e-16j  1.66533454e-15-7.49400542e-16j -3.53883589e-16-8.32667268e-17j  1.38777878e-16-4.16333634e-17j  1.35308431e-15+1.03389519e-15j  1.41553436e-15+1.02695630e-15j  1.55431223e-15+4.92661467e-16j -1.42941214e-15-7.94503352e-16j  5.55111512e-17+2.22044605e-16j  1.07552856e-16-1.38777878e-16j -2.77555756e-17-8.32667268e-17j  1.31838984e-16-1.38777878e-17j  6.93889390e-17-3.46944695e-18j  5.55111512e-17+6.93889390e-18j  2.77555756e-17-6.24500451e-17j -2.77555756e-17-2.08166817e-17j  2.77555756e-17+1.11022302e-16j -4.16333634e-17+1.27068495e-16j  4.16333634e-17+1.52655666e-16j  4.99600361e-16-1.11022302e-16j -3.46944695e-16+5.27355937e-16j  1.